### PR TITLE
Destination Address Selection

### PR DESCRIPTION
**Pull request by psealock**
**Issue**
>The task for Taui will be to implement Destination Address Selection. Currently, the design allows for a single origin to be selected and once you hover over the map, routes appear from the origin to that destination. This causes too much jumping and not a fined grained enough selection for the end user.

Hi all, looking forward to contributing...

### CODE REVIEW

**Comment by psealock** [comment]
**Java error setting up r5**

* Installed Java 8
* I grabbed the latest jar file from the [maven repo](http://maven.conveyal.com/com/conveyal/r5/0.1-SNAPSHOT/) as well as ```static.json``` from your email.
* navigated to jar file location and ran the following:
```bash
$ java -Xmx4g -jar r5-0.1-20151209.223032-30.jar static-server static.json analyst-dev-graphs
```
* Error
```
no main manifest attribute, in r5-0.1-20151209.223032-30.jar
```
* Attempted to execute by pointing to entry point I found in pom.xml, ```com.conveyal.r5.R5Main```
```bash
$ java -Xmx4g -cp r5-0.1-20151209.223032-30.jar com.conveyal.r5.R5Main static-server static.json analyst-dev-graphs
```
* Error
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/Module
```
@trevorgerhardt , have I missed anything? Thanks, I'm a bit out of my element here.

**Comment by trevorgerhardt** [comment]
@psealock responded via email but only cause I hadn't seen this yet. Let's keep communication here and I'll try to make the Java part as smooth as possible :)

**Comment by psealock** [comment]
@trevorgerhardt, Thanks for looking into it. At the moment, I'm running into permission issues with s3. Since I have no credentials for the AWS request, there appears to be an issue with the default [IAM Roles](http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/java-dg-roles.html).

```bash
Exception in thread "main" com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 055DD3066F890D61), S3 Extended Request ID: 8DDxLZ0DksXH9bV8pSsXgUppyfoq1QhJEvTmZMN53lFBBb0SKFYpT/OFRu6R1GRaCC3Pm4dDJqs=
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1219)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:803)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:505)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:317)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3595)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1116)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1005)
	at com.conveyal.r5.transit.TransportNetworkCache.buildNetwork(TransportNetworkCache.java:120)
	at com.conveyal.r5.transit.TransportNetworkCache.getNetwork(TransportNetworkCache.java:58)
	at com.conveyal.r5.publish.StaticServer.main(StaticServer.java:31)
	at com.conveyal.r5.R5Main.main(R5Main.java:29)
```
I'm using the jar you sent me over [dropbox](https://www.dropbox.com/s/tjxm75rr8mt5d77/r5.jar?dl=0) and with the following command:
```bash
$ java -Xmx4g -jar r5.jar static-server static.json analyst-dev-graphs
```
Thanks for the help Trevor. Please let me know if I've missed any steps or can provide more information.

**Comment by trevorgerhardt** [comment]
Hmm I thought `analyst-dev-graphs` was publicly available. Let me change the permissions.

**Comment by trevorgerhardt** [comment]
Ok, added a bucket policy that allows you to retrieve all items in that bucket.

**Comment by psealock** [comment]
Thanks @trevorgerhardt, that worked I'm able to get r5 running locally.

**Comment by psealock** [comment]
**Update**
This is an update on progress, not a final submission. I want to explain what my thoughts are and where I'm headed with this. Feel free to comment at this time or after I'm satisfied with the solution.

**Plan**
>once you hover over the map, routes appear from the origin to that destination

I want to keep the hover functionality, unless
* a destination location is provided in a destination  ```Geocoder``` input or
* a click on the map initializes a destination marker (currently resets origin)

**Progress**
* Updated ```reducers``` to accomodate multiple markers
* Created ```MapMarkers``` class to abstract reusable methods
* Added ```.editorConfig``` to keep whitespace sane

**Questions**
* I've nested ```react-leaflet```'s ```Marker``` class in my new class, ```MapMarkers```. Although, I can see it in React Dev Tools, its icon isn't rendered. @trevorgerhardt, do you know off the top of your head why that might be? Otherwise, I'll dig a bit deeper into that library.

**Comment by trevorgerhardt** [comment]
Looks good to me @psealock! Off the top of my head I'm not sure why the Marker wouldn't be shown.

The hover functionality is cool, but unnecessary and could cause unwanted visual changes. I'd rather the destination and the updated transitive routes only get updated on an input. Since the origin updates on map click, I'd rather we go with this functionality:

1. Origin is selected via map click or geocode.
2. Destination is selected via geocode only. If the map is clicked again, the origin changes.
3. Destination marker is dragged. On drag, the transitive display gets updated like the current hover functionality.

Note: Destination marker **does not** get cleared on origin change. 

Does that make sense?

**Comment by psealock** [comment]
Awesome, makes sense to me.

_Re: Marker not being shown_
```<Marker>``` has to be a direct child of ```<Map>```. Even this DOM representation causes errors
```
<Map>
    <div>
        <Marker />
    </div>
</Map>
```
I'm removing the extra class ```MapMarker``` in favor of a helper function to return ```Marker``` itself. I'll push changes in a few...

**Comment by psealock** [comment]
**Update**
* Fixed Marker error by eliminating wrapping ```Marker``` in a component
* Pulled down latest changes. @trevorgerhardt, FYI pointing the assets to ```dist``` instead of ```static``` broke the build for me. I have not looked into it, so I temporarily reverted that changes for my purposes.

**Comment by trevorgerhardt** [comment]
Ah. I checked in the changes to the production configuration but not the development. I've also needed to hastily change how we pull in config so that it's not checked in each time. What used to be in `src/config.js` now should reside in `config.dev.js` and be attached to `window.taui.config` instead of exported. For example:

```js
window.taui = window.taui || {}

var accessToken = 'pk.eyJ1IjoiY29udmV5YWwiLCJhIjoiMDliQURXOCJ9.9JWPsqJY7dGIdX777An7Pw'
var mapId = 'conveyal.ie3o67m0'

var r5Url = 'http://localhost:4567'

window.taui.config = {
  browsochrones: {
    gridsUrl: 'http://s3.amazonaws.com/analyst-static/indy-baseline/grids',
    originsUrl: r5Url,
    queryUrl: r5Url + '/query.json',
    stopTreesUrl: r5Url + '/stop_trees.dat',
    transitiveNetworkUrl: r5Url + '/transitive.json'
  },
  map: {
    attribution: '&copy <a href="https://www.mapbox.com/map-feedback/">Mapbox</a> &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>',
    center: [39.7691, -86.1570],
    mapbox: {
      accessToken,
      mapId
    },
    url: 'http://api.tiles.mapbox.com/v4/' + mapId + '/{z}/{x}/{y}.png?access_token=' + accessToken,
    zoom: 13
  },
  mapMarker: {
    position: [39.7691, -86.1570]
  }
}
```

**Comment by psealock** [comment]
@trevorgerhardt, I pulled down your latest changes, created ```config.dev.js``` file, and theres a console error when ```dispatch``` is called.
```
Warning: setState(...): Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
```
Any changes to the origin via dragging or entering an address produces the error (even build of the ```master``` branch). I gave an effort to debug but didn't get anywhere in a timely manner.

**Comment by trevorgerhardt** [comment]
Oh whoops! Replaced a `console.log` with a `this.log` before checking in. Should be fixed now!

**Comment by psealock** [comment]
Sweet, thanks

**Comment by psealock** [comment]
**Update**
* Pulled the latest commits. :+1: for sourcemaps
* Created destination ```geocoder``` input
* Enabled ```updateTransitive``` on destination marker drag
* On movement of the origin, ```updateBrowsochrones``` and if a destination marker exists, ```updateTransitive``` as well. More on this later

**Solution**
_criteria_
>
* Origin is selected via map click or geocode.
* Destination is selected via geocode only. If the map is clicked again, the origin changes.
* Destination marker is dragged. On drag, the transitive display gets updated like the current hover functionality.

_result_
destination

**Thoughts**
* If I were to continue this project, my next step would be to decouple ```updateTransitive``` from events in favor of reacting to dispatched actions. The current functionality works because it only gets called on hover, but if you'd like to programmatically call  ```updateTransitive```, you have to manufacture the event (which I did). A better approach is a pure function ```shouldTransitiveUpdate``` in the render method. You can see this deficiency when moving the origin in the build of my code. Transitive should update based on state as opposed to the event created by movement of the origin marker. As a result routes don't refresh until after browsochrones do. I chose not to pursue this endeavor as I felt it out of scope for the project.
* Since the functionality has changed, the UX should change as its a bit awkward. For instance, on page load instructions aren't so clear. Perhaps updating Browsochrones immediately (instead of waiting for movement of the origin) or not initializing the origin marker altogether. 
* Its been a cool project. Thanks for the opportunity to hack around! Any and all commentary is welcome and I look forward to hearing feedback.

**Comment by trevorgerhardt** [comment]
@psealock thanks for the pull! I'm checking out the code today. Looks like it will be an easy merge. I'll follow up with you via email.

**Pull request merged**
